from .mailing import *
from .spam import *
from .userinfo import *
from .help import *
from .crash import *
from .ban import *
from .unban import *
from .get_chat import *
from .give_admin import *
from .chatinfo import *
from .set_prefix import *
from .autoanswer import *
from .notescmd import *